<a href="https://colab.research.google.com/github/DV-11/SpanishDialectDiscrimination/blob/main/Adjective_Data_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trait Adjective Data

To make sure each adjective is used for only one trait, I use this notebook to find duplicates.

In [1]:
import pandas as pd

In [2]:
!git clone https://github.com/DV-11/SpanishDialectDiscrimination.git

Cloning into 'SpanishDialectDiscrimination'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 34 (delta 7), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (34/34), 11.02 MiB | 13.25 MiB/s, done.
Resolving deltas: 100% (7/7), done.

In [3]:
df = pd.read_csv("/content/SpanishDialectDiscrimination/Data/adjective_dataset_v1.csv")

In [4]:
df.head()

,Inteligent_ES,Inteligent_EN,Uninteligent_ES,Uninteligent_EN,SelfConfident_ES,SelfConfident_EN,Insecure_ES,Insecure_EN,Trustworthy_ES,Trustworthy_EN,...,Unfriendly_ES,Unfriendly_EN,Kind_ES,Kind_EN,Unkind_ES,Unkind_EN,Outgoing_ES,Outgoing_EN,Antisocial_ES,Antisocial_EN
0,inteligente,intelligent,tonto,unintelligent,seguro,self-confident,inseguro,insecure,fiable,trustworthy,...,hostil,unfriendly,amable,kind,rudo,unkind,extrovertido,outgoing,introvertido,antisocial
1,listo,smart,torpe,dumb,decidido,confident,inestable,worried,fiel,reliable,...,contrario,icy,cortés,compassionate,brusco,rude,extravertido,social,retraído,detached
2,capaz,clever,incapaz,stupid,aplomado,optimistic,indeciso,nervous,leal,responsible,...,enemigo,cold,atento,benevolent,ordinario,unpleasant,comunicativo,extroverted,tímido,distant
3,ingenioso,quick,inepto,slow,resuelto,assured,vacilante,anxious,confiable,safe,...,adverso,frigid,benévolo,thoughtful,áspero,unfavorable,sociable,extraverted,insociable,unsociable
4,sesudo,brilliant,incompetente,simple,confiado,self-assured,dudoso,upset,fidedigno,true,...,rival,brittle,cariñoso,sympathetic,grosero,inconsiderate,abierto,gregarious,reservado,asocial

# Check for duplitactes between columns

In [5]:
all_adjs = set()
for i in df.columns:
  for j in df[i].unique():
    if j is not None:
      all_adjs.add(j)

In [6]:
repeated_adjs = {}

for i in all_adjs:
  cols = df.columns[df.isin([i]).any()].tolist()
  if len(cols) > 1 and type(i) is not float:
    repeated_adjs[i] = cols

In [7]:
repeated_adjs

{'agradable': ['Friendly_ES', 'Outgoing_ES'],
 'comedido': ['Kind_ES', 'Antisocial_ES'],
 'tratable': ['Friendly_ES', 'Outgoing_ES'],
 'grosero': ['Unfriendly_ES', 'Unkind_ES'],
 'sociable': ['Outgoing_ES', 'Outgoing_EN'],
 'gracious': ['Friendly_EN', 'Kind_EN'],
 'reserved': ['Unfriendly_EN', 'Antisocial_EN'],
 'secure': ['SelfConfident_EN', 'Trustworthy_EN'],
 'cordial': ['Friendly_ES', 'Friendly_EN'],
 'good': ['Trustworthy_EN', 'Kind_EN'],
 'benévolo': ['Friendly_ES', 'Kind_ES'],
 'cerrado': ['Unfriendly_ES', 'Antisocial_ES'],
 'desatento': ['Unfriendly_ES', 'Unkind_ES'],
 'desabrido': ['Unfriendly_ES', 'Unkind_ES'],
 'simpático': ['Friendly_ES', 'Outgoing_ES'],
 'detached': ['Unfriendly_EN', 'Antisocial_EN'],
 'arisco': ['Unfriendly_ES', 'Unkind_ES'],
 'unsociable': ['Unkind_EN', 'Antisocial_EN'],
 'nice': ['Friendly_EN', 'Kind_EN'],
 'warmhearted': ['Friendly_EN', 'Kind_EN'],
 'antipático': ['Unfriendly_ES', 'Unkind_ES'],
 'vivo': ['Inteligent_ES', 'Outgoing_ES'],
 'accesible': ['Friendly_ES', 'Outgoing_ES'],
 'afectuoso': ['Friendly_ES', 'Kind_ES', 'Outgoing_ES'],
 'prudente': ['SelfConfident_ES', 'Antisocial_ES'],
 'rudo': ['Unfriendly_ES', 'Unkind_ES'],
 'dudoso': ['Insecure_ES', 'Untrustworthy_ES'],
 'sweet': ['Friendly_EN', 'Kind_EN'],
 'abierto': ['Friendly_ES', 'Outgoing_ES'],
 'cariñoso': ['Friendly_ES', 'Kind_ES']}

The cell above shows which adjectives appear in multiple columns. The column with the adjective in the highest row keeps it.

# Dataset V2

After manually removing duplicates and finding additional substitute adjectives, I load the new version of the adjectives dataset

In [8]:
df2 = pd.read_csv("/content/SpanishDialectDiscrimination/Data/adjective_dataset_v2.csv")
df2.head()

,Inteligent_ES,Inteligent_EN,Uninteligent_ES,Uninteligent_EN,SelfConfident_ES,SelfConfident_EN,Insecure_ES,Insecure_EN,Trustworthy_ES,Trustworthy_EN,...,Unfriendly_ES,Unfriendly_EN,Kind_ES,Kind_EN,Unkind_ES,Unkind_EN,Outgoing_ES,Outgoing_EN,Antisocial_ES,Antisocial_EN
0,inteligente,intelligent,tonto,unintelligent,seguro,self-confident,inseguro,insecure,fiable,trustworthy,...,hostil,unfriendly,amable,kind,rudo,unkind,extrovertido,outgoing,introvertido,antisocial
1,listo,smart,torpe,dumb,decidido,confident,inestable,worried,fiel,reliable,...,contrario,icy,atento,compassionate,brusco,rude,extravertido,social,retraído,detached
2,capaz,clever,incapaz,stupid,aplomado,optimistic,indeciso,nervous,leal,responsible,...,enemigo,cold,benévolo,benevolent,ordinario,unpleasant,comunicativo,extroverted,tímido,distant
3,ingenioso,quick,inepto,slow,resuelto,assured,vacilante,anxious,confiable,safe,...,adverso,frigid,cariñoso,thoughtful,áspero,unfavorable,sociable,extraverted,insociable,unsociable
4,sesudo,brilliant,incompetente,simple,confiado,self-assured,incierto,upset,fidedigno,true,...,rival,brittle,afectuoso,sympathetic,grosero,inconsiderate,abierto,gregarious,reservado,asocial

In [9]:
all_adjs = set()
for i in df2.columns:
  for j in df2[i].unique():
    if j is not None:
      all_adjs.add(j)

In [10]:
repeated_adjs = {}

for i in all_adjs:
  cols = df2.columns[df2.isin([i]).any()].tolist()
  if len(cols) > 1 and type(i) is not float:
    repeated_adjs[i] = cols

In [11]:
repeated_adjs

{'sociable': ['Outgoing_ES', 'Outgoing_EN'],
 'cordial': ['Friendly_ES', 'Friendly_EN']}

No duplicates between columns. The two results in the cell above, 'cordial' and 'sociable', are not indicating the same adjective being used for multiple traits, but rather an adjective that is used both in Spanish and in English.

In [12]:
all_adjs = set()
for i in df2.columns:
  for j in df2[i].duplicated():
    if j == True:
      print(i)

The cell above makes sure that each trait has 20 unique adjectives, without any repeated ones.