In [1]:
from huggingface_hub import login

hf_token = "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"
login(hf_token)

/home/dvaleromar/Desktop/SpanishDialectDiscrimination/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from transformers import AutoProcessor, Gemma3ForConditionalGeneration
from PIL import Image
import requests
import torch
import pandas as pd
import numpy as np
import random
import datetime

# Load Job Title Data

In [8]:
job_title_data = pd.read_csv('Data/Job_Title_Data.csv')

job_title_data.head()

,Country,City,Original,Job_ES,Job_EN,Position,Link
0,Spain,Madrid,Administrativo Contable,Administrativo contable,Accounting administrator,High,https://es.indeed.com/pagead/clk?mo=r&ad=-6NYl...
1,Spain,Madrid,Gerente Cobranza,Gerente de cobranza,Collections manager,High,https://es.indeed.com/pagead/clk?mo=r&ad=-6NYl...
2,Spain,Madrid,Asesor Inmobiliario en Century 21 ABC Gallery....,Asesor Inmobiliario,Real estate advisor,High,https://es.indeed.com/pagead/clk?mo=r&ad=-6NYl...
3,Spain,Madrid,Maestro as de educacion infantil in Irlanda,Maestro de educación infantil,Early-childhood education teacher,High,https://es.indeed.com/pagead/clk?mo=r&ad=-6NYl...
4,Spain,Madrid,Director/a de proyecto IT Senior (f/m),Director de proyecto IT Senior,IT Senior Project manager,High,https://es.indeed.com/rc/clk?jk=4a486d55f56c26...

In [9]:
jobs_en = job_title_data['Job_EN'].values
np.random.shuffle(jobs_en)
jobs_sp = job_title_data['Job_ES'].values
np.random.shuffle(jobs_sp)

/tmp/ipykernel_112574/3423448375.py:2: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs_en)
/tmp/ipykernel_112574/3423448375.py:4: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs_sp)

# Load Sentence Data

In [10]:
sen_df = pd.read_csv("Data/Working_Sentence_Dataset.csv")

sen_df['Sentence_ID'] = range(len(sen_df))
sen_df['Sentence_ID'] += 1

sen_df.head()

,Sentence_ID,Text ID,Line,Speaker,Raw,PS,PS_Check,PS_Note,MS,MS_Check,MS_Note,English,Type
0,1,ALCA_H11_037,10,B,¿qué has hecho hoy? / cuéntame <silencio/> cur...,¿Qué has hecho hoy? Cuéntame - Currar y pasar ...,NaN,NaN,¿Qué hiciste hoy? Cuéntame - Chambear y pasar ...,NaN,NaN,What did you do today? Tell me - I worked and ...,B
1,2,ALCA_H11_037,11,I,he cambiado / porque la otra vez / la niña est...,"He cambiado, porque la niña estaba en el coleg...",NaN,NaN,"Cambié, porque la niña estaba en la escuela, p...",X,"Cambié, porque la niña estaba en la escuela, p...","I changed, because the girl was in school, but...",B
2,3,ALCA_H11_037,12,I,hoy me ha tocado / irme con el coche a un pueb...,Hoy me ha tocado irme con el coche a un pueblo...,NaN,NaN,Hoy me tocó irme con el carro a un pueblo a re...,NaN,NaN,Today I had to go to a town by car to deliver ...,Both
3,4,ALCA_H11_037,14,I,normalmente si estoy solo si tengo jaleo pues ...,"Normalmente, si estoy solo o si tengo jaleo, p...",NaN,NaN,"Normalmente, si estoy solo o si hay alboroto, ...",NaN,NaN,"Usually, if I'm alone or if there's a commotio...",L
4,5,ALCA_H11_037,16,I,le vamos a coger el gustillo,Le vamos a coger el gustillo,NaN,NaN,Le vamos a agarrar el gustito,NaN,NaN,We're going to take a liking to it,L

In [11]:
sen_only = sen_df[['Sentence_ID','PS','MS']]
sen_only.head()

,Sentence_ID,PS,MS
0,1,¿Qué has hecho hoy? Cuéntame - Currar y pasar ...,¿Qué hiciste hoy? Cuéntame - Chambear y pasar ...
1,2,"He cambiado, porque la niña estaba en el coleg...","Cambié, porque la niña estaba en la escuela, p..."
2,3,Hoy me ha tocado irme con el coche a un pueblo...,Hoy me tocó irme con el carro a un pueblo a re...
3,4,"Normalmente, si estoy solo o si tengo jaleo, p...","Normalmente, si estoy solo o si hay alboroto, ..."
4,5,Le vamos a coger el gustillo,Le vamos a agarrar el gustito

# Run Model

In [12]:
model_id = "google/gemma-3-12b-it"

In [13]:
model = Gemma3ForConditionalGeneration.from_pretrained(
    model_id, device_map="auto"
).eval()

processor = AutoProcessor.from_pretrained(model_id)

Fetching 5 files: 100%|██████████| 5/5 [00:00<00:00, 56527.01it/s]
Loading weights: 100%|██████████| 1065/1065 [00:02<00:00, 355.12it/s, Materializing param=model.vision_tower.vision_model.post_layernorm.weight]

# Query Model

In [14]:
sp_prompt = "Aqui tienes una lista de empleos. Por cada empleo, escoge un escritor - A o B - que sea mas apropiado para el empleo y escribelo a su lado sin explicacion adicional. Pon una coma despues de cada escritor. Los empleos son son: "
en_prompt = "Here is a list of jobs. For each job, choose a writer - A o B - that is more appropriate for the job and write it next to the job without further explanation. Put a comma after each writer. The jobs are: "

sp_promt_exp = "Aqui tienes una lista de empleos. Por cada empleo, escoge un escritor - A o B - que sea mas apropiado para el empleo y escribelo a su lado sin explicacion adicional. "
en_prompt_exp = "Here is a list of jobs. For each job, choose a writer - A o B - that is more appropriate for the job and write it next to the job without further explanation. "

p_ps_a_sp = " El escritor A usa español peninsular y el escritor B usa español mexicano. Pon una coma despues de cada escritor. Los adjetivos son son: "
p_ms_a_sp = " El escritor A usa español mexicano y el escritor B usa español peninsular. Pon una coma despues de cada escritor. Los adjetivos son son: "

p_ps_a_en = "Writer A uses Peninsular Spanish and writer B uses Mexican Spanish. Put a comma after each writer. The adjectivess are: "
p_ms_a_en = "Writer A uses Mexican Spanish and writer B uses Peninsular Spanish. Put a comma after each writer. The adjectivess are: "

In [ ]:
def query_DT(language, mode):

    if language == 'Spanish':
        jobs = jobs_sp
        lan = 'sp'
        sys_msg = "Eres un asistente."
    elif language == 'English':
        jobs = jobs_en
        lan = 'en'
        sys_msg = "You are an assistant."
    else:
        raise Exception('No valid trait')

    if mode == 'Implicit':
        m = ''
    elif mode == 'Explicit':
        m = '_exp'
    else:
        raise Exception('No valid mode')


    response_data = []

    for i in range(101,201):

        run_data = []
        run_data.append(i)


        # get current sentence
        current_row = sen_only.loc[sen_only['Sentence_ID'] == i]
        ps_sen = current_row['PS'][i-1]
        ms_sen = current_row['MS'][i-1]


        # randomise job list
        np.random.shuffle(jobs)
        job_str = ', '.join(map(str,jobs))



        # write full prompt, alternatig order of ps and ms sentences
        if i%2 == 1:

            if mode == 'Explicit':
                if language == 'Spanish':
                    full_prompt = sp_promt_exp + "El escritor A usa español peninsular y el escritor B usa español mexicano. Pon una coma despues de cada escritor. Los empleos son son: " + job_str
                elif language == 'English':
                    full_prompt = en_promt_exp + "Writer A uses Peninsular Spanish and writer B uses Mexican Spanish. Put a comma after each writer. The jobs are: " + job_str
            elif mode == 'Implicit':
                if language == 'Spanish':
                    full_prompt = sp_prompt + ' ' + job_str+ '. ' + "A: " + ps_sen + " B: " + ms_sen
                elif language == 'English':
                    full_prompt = en_prompt + ' ' + job_str+ '. ' + "A: " + ps_sen + " B: " + ms_sen
            run_data.append("PS")
            run_data.append("MS")
        else:
            if mode == 'Explicit':
                if language == 'Spanish':
                    full_prompt = sp_promt_exp + "El escritor A usa español mexicano y el escritor B usa español peninsular. Pon una coma despues de cada escritor. Los empleos son son: " + job_str
                elif language == 'English':
                    full_prompt = en_promt_exp + "Writer A uses Mexican Spanish and writer B uses Peninsular Spanish. Put a comma after each writer. The jobs are: " + job_str
            elif mode == 'Implicit':
                if language == 'Spanish':
                    full_prompt = sp_prompt + ' ' + job_str+ '. ' + "A: " + ms_sen + " B: " + ps_sen
                elif language == 'English':
                    full_prompt = en_prompt + ' ' + job_str+ '. ' + "A: " + ms_sen + " B: " + ps_sen
            run_data.append("MS")
            run_data.append("PS")
        run_data.append(full_prompt)

        # query model
        messages = [
            {
                "role": "system",
                "content": [{"type": "text", "text": sys_msg}]
            },
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": full_prompt}
                ]
            }
        ]

        inputs = processor.apply_chat_template(
            messages, add_generation_prompt=True, tokenize=True,
            return_dict=True, return_tensors="pt"
        ).to(model.device, dtype=torch.bfloat16)

        input_len = inputs["input_ids"].shape[-1]

        with torch.inference_mode():
            generation = model.generate(**inputs, max_new_tokens=500, do_sample=False)
            generation = generation[0][input_len:]

        decoded = processor.decode(generation, skip_special_tokens=True)
        run_data.append(decoded)

        run_data.append(datetime.datetime.now().strftime("%x"))

        # append results of run
        response_data.append(run_data)

    response_df = pd.DataFrame(response_data, columns=["sen_id", "A", "B", "prompt", "response", "date"])

    file_name = 'results_gemma_DecisTask_' + lan + m +'_p3.csv'

    response_df.to_csv(file_name, index=False)

In [16]:
query_DT('Spanish', 'Implicit')

/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
The following generation flags are not valid and may be ignored: ['top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)
/tmp/ipykernel_112574/168535679.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)

In [21]:
query_DT('English', 'Implicit')

/tmp/ipykernel_112574/3989348849.py:37: UserWarning: you are shuffling a 'StringArray' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(jobs)

In [ ]:
# query_DT('Spanish', 'Explicit')

In [ ]:
# query_DT('English', 'Explicit')

'Hospital administrator, B\nCashier - Stock clerk, A\nAccounting advisor, B\nPsychologist, B\nChauffeur, A\nArchive documentarist, B\nDirector of operations, B\nAssistant store branch manager, A\nJunior Data Analyst, B\nTelecommunications installer, A\nIce cream shop attendant, A\nSelf-service assistant, A\nStore shift manager, A\nSecurity guard, A\nKitchen assistant, A\nEvent and conference coordinator, B\nWarehouse office staff, A\nField auditor, B\nBeauty products advisor, A\nVehicle mechanic, A\nBarista trainee, A\nReal estate advisor, B\nBookstore manager, A\nIT Senior Project manager, B\nPharmacy manager, B\nProduction manager, B\nAdministrative and financial analyst, B\nButcher Shop attendant, A\nAir conditioner installer, A\nHairdresser, A\nOrder picker, A\nCollections manager, B\nJapanese cuisine cook, A\nHotel receptionist, A\nDog groomer, A\nSurgery instrument technician, B\nCounter sales clerk, A\nPet shop assistant, A\nPrivate school principal, B\nRisk management and data security specialist, B\nPastry shop attendant, A\nWarehouse assistant, A\nCleaning staff, A\nAccounting administrator, B\nStore branch manager, A\nCustomer service agent, A\nMarketing & PR manager, B\nFinancial advisor, B\nEarly-childhood education teacher, B\nMental health assistant, B\nBank teller, A\nMotorcycle delivery driver, A\nHuman resources manager, B\nParcel delivery driver, A'